#!/usr/bin/env node
var fs = require('fs'),
    net = require('net'),
    os = require('os'),
    server = net.createServer(connect);

var slash;    
var homePath = (function() {
  var isWin = process.platform === 'win32',
      isMac = process.platform === 'darwin',
      home = isWin ? process.env['USERPROFILE'] :
        isMac ? '/Users/' : '/home/';

  slash = isWin ? '\\' : '/';

  return home.substring(0, home.lastIndexOf(slash));
})();

function User(name) {
  this.name = name;
}

User.prototype = {
  name: '',

  errors: {},

  get home () {
    return homePath + slash + this.name;
  },

  get planfile () {
    return this.home + slash + '.plan';
  },

  get projectfile () {
    return this.home + slash + '.project';
  },

  get plan () {
    return this._plan;
  },

  set plan (p) {
    this._plan = p;
  },

  get project () {
    return this._project;
  },

  set project (p) {
    this._project = p;
  },

  getPlan: function(cb) {
    fs.readFile(this.planfile, cb);
  },

  getProject: function(cb) {
    fs.readFile(this.projectfile, cb);
  },

  getPlanAndProject: function(cb, type, err, data) {
    var self = this, compose;

    if(typeof type === 'undefined') {
      compose = function(t) {
        return self.getPlanAndProject.bind(self, cb, t);
      }
      self.getPlan(compose('plan'));
      self.getProject(compose('project'));

      return;
    }

    self[type] = data || null;
    if(err)
      self.errors[type] = err;

    if(typeof self.plan !== "undefined" && typeof self.project !== "undefined") {
      if(Object.keys(self.errors).length > 0)
        cb(self.errors, self.plan, self.project);
      else
        cb(null, self.plan, self.project);
    }
  }
};

function Request(raw) {
  var data = raw.split('\r\n');
  if(data) {
    this.user = new User(data[0]);
  }
}

Request.prototype = {
  user: ''
};

function Response(request) {
  this.req = request;
}

Response.prototype = {
  reply: function(cb) {
    var self = this;
    var user = self.req.user;
    user.getPlanAndProject(function(errs, data) {
      var msg = '';

      if(!errs) {
        msg = data;
      }

     cb(msg);
    });
  },

  parseError: function(plan, err) {
    var msg;

    switch(err.code) {
      case 'ENOENT':
        msg = "User doesn't have a plan.\n";
        break;
      default:
        console.log('Plan: ' + plan + ', Code: ' + err.code);
        msg = "Unable to open the user's plan.";
        break;
    }
    
    return msg;
  }
};

function connect (stream) {
  stream.setEncoding('utf8');
  stream.on('connect', function() {
    
  });

  stream.on('data', function(data) {
    var req = new Request(data),
        resp = new Response(req);
    
    resp.reply(function(msg) {
      stream.write(msg);
      stream.end();
    });
  });
}


server.listen(79);

